services:
  db:
    image: mysql:8.0
    container_name: mysqlCRUD2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./dumpDB.sql:/docker-entrypoint-initdb.d/dumpDB.sql
